/**
 * Provisioning API
 * The provisioning service will be used to create objects in configuration server in a way that is consistent with the BEC model.  The \"users\" resource will be used to perform CRUD operations on config server person objects. Note that this API will extend the low level configuration server API to add additional functionality that will allow persons to be created in a way that makes them immediately useable in BEC. Operations on this resource may result in other configuration objects being modified as well. 
 *
 * OpenAPI spec version: 9.0.000.00.646
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['provisioning/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ProvisioningApi) {
      root.ProvisioningApi = {};
    }
    root.ProvisioningApi.Login = factory(root.ProvisioningApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Login model module.
   * @module provisioning/model/Login
   * @version 9.0.000.00.646
   */

  /**
   * Constructs a new <code>Login</code>.
   * @alias module:provisioning/model/Login
   * @class
   * @param domainUsername {String} User unique login in form: domain.com\\login  Effect: Controls the value of the corresponding CfgPerson attribute 
   * @param password {String} Password as plain text.  Effect: Controls the value of the corresponding CfgPerson attribute 
   */
  var exports = function(domainUsername, password) {
    var _this = this;

    _this['domain_username'] = domainUsername;
    _this['password'] = password;
  };

  /**
   * Constructs a <code>Login</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:provisioning/model/Login} obj Optional instance to populate.
   * @return {module:provisioning/model/Login} The populated <code>Login</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('domain_username')) {
        obj['domain_username'] = ApiClient.convertToType(data['domain_username'], 'String');
      }
      if (data.hasOwnProperty('password')) {
        obj['password'] = ApiClient.convertToType(data['password'], 'String');
      }
    }
    return obj;
  }

  /**
   * User unique login in form: domain.com\\login  Effect: Controls the value of the corresponding CfgPerson attribute 
   * @member {String} domain_username
   * @default 'domain.com\login'
   */
  exports.prototype['domain_username'] = 'domain.com\login';
  /**
   * Password as plain text.  Effect: Controls the value of the corresponding CfgPerson attribute 
   * @member {String} password
   * @default 'password'
   */
  exports.prototype['password'] = 'password';



  return exports;
}));


