/**
 * Provisioning API
 * The provisioning service will be used to create objects in configuration server in a way that is consistent with the BEC model.  The \"users\" resource will be used to perform CRUD operations on config server person objects. Note that this API will extend the low level configuration server API to add additional functionality that will allow persons to be created in a way that makes them immediately useable in BEC. Operations on this resource may result in other configuration objects being modified as well. 
 *
 * OpenAPI spec version: 9.0.000.00.646
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['provisioning/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ProvisioningApi) {
      root.ProvisioningApi = {};
    }
    root.ProvisioningApi.OptionsPut = factory(root.ProvisioningApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The OptionsPut model module.
   * @module provisioning/model/OptionsPut
   * @version 9.0.000.00.646
   */

  /**
   * Constructs a new <code>OptionsPut</code>.
   * @alias module:provisioning/model/OptionsPut
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>OptionsPut</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:provisioning/model/OptionsPut} obj Optional instance to populate.
   * @return {module:provisioning/model/OptionsPut} The populated <code>OptionsPut</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('newOptions')) {
        obj['newOptions'] = ApiClient.convertToType(data['newOptions'], Object);
      }
      if (data.hasOwnProperty('changedOptions')) {
        obj['changedOptions'] = ApiClient.convertToType(data['changedOptions'], Object);
      }
      if (data.hasOwnProperty('deletedOptions')) {
        obj['deletedOptions'] = ApiClient.convertToType(data['deletedOptions'], Object);
      }
    }
    return obj;
  }

  /**
   * New CloudCluster app Options.  Effect: Adds sections, keys and values in CloudCluster/Options 
   * @member {Object} newOptions
   */
  exports.prototype['newOptions'] = undefined;
  /**
   * Changed CloudCluster app Options.  Effect: Updates existing values in CloudCluster/Options 
   * @member {Object} changedOptions
   */
  exports.prototype['changedOptions'] = undefined;
  /**
   * Deleted CloudCluster app Options.  Effect: Deletes sections, keys and values in CloudCluster/Options 
   * @member {Object} deletedOptions
   */
  exports.prototype['deletedOptions'] = undefined;



  return exports;
}));


