/**
 * Provisioning API
 * The provisioning service will be used to create objects in configuration server in a way that is consistent with the BEC model. The \"users\" resource will be used to perform CRUD operations on config server person objects. Note that this API will extend the low level configuration server API to add additional functionality that will allow persons to be created in a way that makes them immediately useable in BEC. Operations on this resource may result in other configuration objects being modified as well. 
 *
 * OpenAPI spec version: 9.0.000.06.1279
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ApiAuditSuccessResponse', 'model/ApiErrorResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ApiAuditSuccessResponse'), require('../model/ApiErrorResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.ProvisioningApi) {
      root.ProvisioningApi = {};
    }
    root.ProvisioningApi.AuditApi = factory(root.ProvisioningApi.ApiClient, root.ProvisioningApi.ApiAuditSuccessResponse, root.ProvisioningApi.ApiErrorResponse);
  }
}(this, function(ApiClient, ApiAuditSuccessResponse, ApiErrorResponse) {
  'use strict';

  /**
   * Audit service.
   * @module api/AuditApi
   * @version 9.0.000.06.1279
   */

  /**
   * Constructs a new AuditApi. 
   * @alias module:api/AuditApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Retrieves audit data
     * The GET operation will fetch Audit API with filters
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit Limit number of users to fetch
     * @param {module:model/String} opts.asc Sort results ascending/descending (default to desc)
     * @param {String} opts.orderBy comma-separated list of fields to sort on, supported: id, createdAt, msg, username  (default to id)
     * @param {String} opts.username Only users with exact match will pass
     * @param {String} opts.auditId Only one row will be displayed with specified ID
     * @param {String} opts.auditFileId If specified, sends raw file data with content-type application/octet-stream for specified file-id. 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ApiAuditSuccessResponse} and HTTP response
     */
    this.getAuditInfoWithHttpInfo = function(opts) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'limit': opts['limit'],
        'asc': opts['asc'],
        'orderBy': opts['orderBy'],
        'username': opts['username'],
        'audit_id': opts['auditId'],
        'audit_file_id': opts['auditFileId'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ApiAuditSuccessResponse;

      return this.apiClient.callApi(
        '/audit', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Retrieves audit data
     * The GET operation will fetch Audit API with filters
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit Limit number of users to fetch
     * @param {module:model/String} opts.asc Sort results ascending/descending (default to desc)
     * @param {String} opts.orderBy comma-separated list of fields to sort on, supported: id, createdAt, msg, username  (default to id)
     * @param {String} opts.username Only users with exact match will pass
     * @param {String} opts.auditId Only one row will be displayed with specified ID
     * @param {String} opts.auditFileId If specified, sends raw file data with content-type application/octet-stream for specified file-id. 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ApiAuditSuccessResponse}
     */
    this.getAuditInfo = function(opts) {
      return this.getAuditInfoWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
