/**
 * Provisioning API
 * The provisioning service will be used to create objects in configuration server in a way that is consistent with the BEC model. The \"users\" resource will be used to perform CRUD operations on config server person objects. Note that this API will extend the low level configuration server API to add additional functionality that will allow persons to be created in a way that makes them immediately useable in BEC. Operations on this resource may result in other configuration objects being modified as well. 
 *
 * OpenAPI spec version: 9.0.000.00.1086
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ApiErrorResponse', 'model/GetObjectsSuccessResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ApiErrorResponse'), require('../model/GetObjectsSuccessResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.ProvisioningApi) {
      root.ProvisioningApi = {};
    }
    root.ProvisioningApi.ObjectsApi = factory(root.ProvisioningApi.ApiClient, root.ProvisioningApi.ApiErrorResponse, root.ProvisioningApi.GetObjectsSuccessResponse);
  }
}(this, function(ApiClient, ApiErrorResponse, GetObjectsSuccessResponse) {
  'use strict';

  /**
   * Objects service.
   * @module api/ObjectsApi
   * @version 9.0.000.00.1086
   */

  /**
   * Constructs a new ObjectsApi. 
   * @alias module:api/ObjectsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Read DNs or Agent Groups
     * The GET operation will fetch objects from configuration server, possible with filters
     * @param {String} objectType Object type - &#39;dns&#39; or &#39;agent-groups&#39;
     * @param {Object} opts Optional parameters
     * @param {String} opts.dnType DN type if object_type &#x3D; &#39;dns&#39; (e.g. CFGRoutingPoint). Refer Configuration Server API docs.
     * @param {module:model/String} opts.groupType Agent Group type if object_type &#x3D; &#39;agent-groups&#39;.
     * @param {Number} opts.limit Limit number of objects to fetch
     * @param {Number} opts.offset Skip first N matches
     * @param {String} opts.searchTerm Part of a key in CFGDN or CfgAgentGroup. 
     * @param {String} opts.searchKey A keypath in CFGDN or CfgAgentGroup to compare with search_term. 
     * @param {String} opts.matchMethod Method to match the search_term (&#39;includes&#39;, &#39;startsWith&#39;, &#39;endsWith&#39;, &#39;isEqual&#39;).  (default to includes)
     * @param {String} opts.sortKey A keypath in CFGDN or CfgAgentGroup to sort by. 
     * @param {Boolean} opts.sortAscending &#39;true&#39; to sort ascenfing, &#39;false&#39; to sort descending.  (default to true)
     * @param {String} opts.sortMethod Case sensitive, case insensitive or numeric.  (default to caseSensitive)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GetObjectsSuccessResponse} and HTTP response
     */
    this.getObjectWithHttpInfo = function(objectType, opts) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'objectType' is set
      if (objectType === undefined || objectType === null) {
        throw new Error("Missing the required parameter 'objectType' when calling getObject");
      }


      var pathParams = {
        'object_type': objectType
      };
      var queryParams = {
        'dn_type': opts['dnType'],
        'group_type': opts['groupType'],
        'limit': opts['limit'],
        'offset': opts['offset'],
        'search_term': opts['searchTerm'],
        'search_key': opts['searchKey'],
        'match_method': opts['matchMethod'],
        'sort_key': opts['sortKey'],
        'sort_ascending': opts['sortAscending'],
        'sort_method': opts['sortMethod'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = GetObjectsSuccessResponse;

      return this.apiClient.callApi(
        '/objects/{object_type}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Read DNs or Agent Groups
     * The GET operation will fetch objects from configuration server, possible with filters
     * @param {String} objectType Object type - &#39;dns&#39; or &#39;agent-groups&#39;
     * @param {Object} opts Optional parameters
     * @param {String} opts.dnType DN type if object_type &#x3D; &#39;dns&#39; (e.g. CFGRoutingPoint). Refer Configuration Server API docs.
     * @param {module:model/String} opts.groupType Agent Group type if object_type &#x3D; &#39;agent-groups&#39;.
     * @param {Number} opts.limit Limit number of objects to fetch
     * @param {Number} opts.offset Skip first N matches
     * @param {String} opts.searchTerm Part of a key in CFGDN or CfgAgentGroup. 
     * @param {String} opts.searchKey A keypath in CFGDN or CfgAgentGroup to compare with search_term. 
     * @param {String} opts.matchMethod Method to match the search_term (&#39;includes&#39;, &#39;startsWith&#39;, &#39;endsWith&#39;, &#39;isEqual&#39;).  (default to includes)
     * @param {String} opts.sortKey A keypath in CFGDN or CfgAgentGroup to sort by. 
     * @param {Boolean} opts.sortAscending &#39;true&#39; to sort ascenfing, &#39;false&#39; to sort descending.  (default to true)
     * @param {String} opts.sortMethod Case sensitive, case insensitive or numeric.  (default to caseSensitive)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GetObjectsSuccessResponse}
     */
    this.getObject = function(objectType, opts) {
      return this.getObjectWithHttpInfo(objectType, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
