/**
 * Provisioning API
 * The provisioning service will be used to create objects in configuration server in a way that is consistent with the BEC model. The \"users\" resource will be used to perform CRUD operations on config server person objects. Note that this API will extend the low level configuration server API to add additional functionality that will allow persons to be created in a way that makes them immediately useable in BEC. Operations on this resource may result in other configuration objects being modified as well. 
 *
 * OpenAPI spec version: 9.0.000.75.4131
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PostPermissionsDataDataObjectIds'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PostPermissionsDataDataObjectIds'));
  } else {
    // Browser globals (root is window)
    if (!root.ProvisioningApi) {
      root.ProvisioningApi = {};
    }
    root.ProvisioningApi.PostPermissionsDataData = factory(root.ProvisioningApi.ApiClient, root.ProvisioningApi.PostPermissionsDataDataObjectIds);
  }
}(this, function(ApiClient, PostPermissionsDataDataObjectIds) {
  'use strict';




  /**
   * The PostPermissionsDataData model module.
   * @module model/PostPermissionsDataData
   * @version 9.0.000.75.4131
   */

  /**
   * Constructs a new <code>PostPermissionsDataData</code>.
   * @alias module:model/PostPermissionsDataData
   * @class
   * @param objectIds {Array.<module:model/PostPermissionsDataDataObjectIds>} Array of object DBIDs to query permissions. 
   */
  var exports = function(objectIds) {
    var _this = this;



    _this['objectIds'] = objectIds;
  };

  /**
   * Constructs a <code>PostPermissionsDataData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PostPermissionsDataData} obj Optional instance to populate.
   * @return {module:model/PostPermissionsDataData} The populated <code>PostPermissionsDataData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('dn_type')) {
        obj['dn_type'] = ApiClient.convertToType(data['dn_type'], 'String');
      }
      if (data.hasOwnProperty('folder_type')) {
        obj['folder_type'] = ApiClient.convertToType(data['folder_type'], 'String');
      }
      if (data.hasOwnProperty('objectIds')) {
        obj['objectIds'] = ApiClient.convertToType(data['objectIds'], [PostPermissionsDataDataObjectIds]);
      }
    }
    return obj;
  }

  /**
   * If the object_type is 'dns', then you may specify the DN type (for example, CFGRoutingPoint). This parameter does not affect request results but may increase performance For possible values, see [CfgDNType](https://docs.genesys.com/Documentation/PSDK/9.0.x/ConfigLayerRef/CfgDNType) in the Platform SDK documentation. 
   * @member {String} dn_type
   */
  exports.prototype['dn_type'] = undefined;
  /**
   * If the object_type is 'folders', then you may specify the object type of the folders  (for example, CFGPerson). This parameter does not affect request results but may increase performance For possible values, see [CfgObjectType](https://docs.genesys.com/Documentation/PSDK/9.0.x/ConfigLayerRef/CfgObjectType) in the Platform SDK documentation. 
   * @member {String} folder_type
   */
  exports.prototype['folder_type'] = undefined;
  /**
   * Array of object DBIDs to query permissions. 
   * @member {Array.<module:model/PostPermissionsDataDataObjectIds>} objectIds
   */
  exports.prototype['objectIds'] = undefined;



  return exports;
}));


