/**
 * Provisioning API
 * The provisioning service will be used to create objects in configuration server in a way that is consistent with the BEC model. The \"users\" resource will be used to perform CRUD operations on config server person objects. Note that this API will extend the low level configuration server API to add additional functionality that will allow persons to be created in a way that makes them immediately useable in BEC. Operations on this resource may result in other configuration objects being modified as well. 
 *
 * OpenAPI spec version: 9.0.000.75.4131
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ApiErrorResponse', 'model/GetWhitelistResponse', 'model/PutWhitelistResponse', 'model/WhitelistBodyData', 'model/WhitelistDeleteBodyData', 'model/WhitelistPutBodyData'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ApiErrorResponse'), require('../model/GetWhitelistResponse'), require('../model/PutWhitelistResponse'), require('../model/WhitelistBodyData'), require('../model/WhitelistDeleteBodyData'), require('../model/WhitelistPutBodyData'));
  } else {
    // Browser globals (root is window)
    if (!root.ProvisioningApi) {
      root.ProvisioningApi = {};
    }
    root.ProvisioningApi.WhitelistApi = factory(root.ProvisioningApi.ApiClient, root.ProvisioningApi.ApiErrorResponse, root.ProvisioningApi.GetWhitelistResponse, root.ProvisioningApi.PutWhitelistResponse, root.ProvisioningApi.WhitelistBodyData, root.ProvisioningApi.WhitelistDeleteBodyData, root.ProvisioningApi.WhitelistPutBodyData);
  }
}(this, function(ApiClient, ApiErrorResponse, GetWhitelistResponse, PutWhitelistResponse, WhitelistBodyData, WhitelistDeleteBodyData, WhitelistPutBodyData) {
  'use strict';

  /**
   * Whitelist service.
   * @module api/WhitelistApi
   * @version 9.0.000.75.4131
   */

  /**
   * Constructs a new WhitelistApi. 
   * @alias module:api/WhitelistApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Delete Address from Whitelist.
     * Delete exist IP address.
     * @param {Object} opts Optional parameters
     * @param {module:model/WhitelistDeleteBodyData} opts.data IP address ids to delete.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PutWhitelistResponse} and HTTP response
     */
    this.deleteWhitelistWithHttpInfo = function(opts) {
      opts = opts || {};
      var postBody = opts['data'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = PutWhitelistResponse;

      return this.apiClient.callApi(
        '/whitelist', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Delete Address from Whitelist.
     * Delete exist IP address.
     * @param {Object} opts Optional parameters
     * @param {module:model/WhitelistDeleteBodyData} opts.data IP address ids to delete.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PutWhitelistResponse}
     */
    this.deleteWhitelist = function(opts) {
      return this.deleteWhitelistWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Whitelist.
     * Receive full whitelist.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GetWhitelistResponse} and HTTP response
     */
    this.getWhitelistWithHttpInfo = function() {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = GetWhitelistResponse;

      return this.apiClient.callApi(
        '/whitelist', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get Whitelist.
     * Receive full whitelist.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GetWhitelistResponse}
     */
    this.getWhitelist = function() {
      return this.getWhitelistWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Post Address(-es) to Whitelist.
     * Add new address(-es).
     * @param {Object} opts Optional parameters
     * @param {module:model/WhitelistBodyData} opts.data Add new IP address or list of IP addresses when array.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GetWhitelistResponse} and HTTP response
     */
    this.postWhitelistWithHttpInfo = function(opts) {
      opts = opts || {};
      var postBody = opts['data'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = GetWhitelistResponse;

      return this.apiClient.callApi(
        '/whitelist', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Post Address(-es) to Whitelist.
     * Add new address(-es).
     * @param {Object} opts Optional parameters
     * @param {module:model/WhitelistBodyData} opts.data Add new IP address or list of IP addresses when array.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GetWhitelistResponse}
     */
    this.postWhitelist = function(opts) {
      return this.postWhitelistWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update Address in Whitelist.
     * Update exist IP address.
     * @param {Object} opts Optional parameters
     * @param {module:model/WhitelistPutBodyData} opts.data IP address object to update.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PutWhitelistResponse} and HTTP response
     */
    this.putWhitelistWithHttpInfo = function(opts) {
      opts = opts || {};
      var postBody = opts['data'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = PutWhitelistResponse;

      return this.apiClient.callApi(
        '/whitelist', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Update Address in Whitelist.
     * Update exist IP address.
     * @param {Object} opts Optional parameters
     * @param {module:model/WhitelistPutBodyData} opts.data IP address object to update.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PutWhitelistResponse}
     */
    this.putWhitelist = function(opts) {
      return this.putWhitelistWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
